#pragma once

// SDL-local service surface implemented only by neo1_platform_sdl.c. It mixes
// window lifecycle, shared-grid presentation, input events, time, and raw block
// I/O; it is not the intended portable machine or future cross-target platform
// API.

#include <stdbool.h>
#include <stdint.h>

// Initialize SDL window/event state, clear the SDL terminal, and open or create
// the raw disk image selected by NEO1_SDL_DISK. Failures are logged, not returned.
void neo1_platform_init(int width, int height, const char* title);
// Close the raw image and destroy SDL renderer/window state.
void neo1_platform_shutdown(void);
// Redraw the shared terminal grid using the SDL renderer and present it.
void neo1_platform_present(void);
// Consume one machine display byte: strip bit 7, treat CR as newline, ignore LF,
// erase one cell for Backspace, and ignore other bytes below $20. Unlike Pico,
// form feed does not clear this terminal and $7F is accepted as a glyph.
void neo1_platform_put_char(uint8_t ch);
// Consume and clear a Ctrl-R reset request generated by SDL events.
bool neo1_platform_should_reset(void);
// Pump events until one injectable key is found. Printable text comes from
// SDL_TEXTINPUT; Return and Backspace come from KEYDOWN. Ctrl-L clears only the
// host terminal. Outputs are initialized to zero/false on every call.
bool neo1_platform_poll_key(uint8_t* out_apple1_keycode, bool* out_pressed);
// Return SDL's monotonic performance counter converted to microseconds.
uint64_t neo1_platform_time_us(void);
// Yield the runner thread for at least the requested whole milliseconds.
void neo1_platform_sleep_ms(uint32_t milliseconds);
// Transfer `count` contiguous 512-byte sectors to/from the one host image.
// Writes flush before reporting success; reads require the full byte count.
bool neo1_platform_disk_read(uint32_t lba, uint8_t* buf, uint32_t count);
bool neo1_platform_disk_write(uint32_t lba, const uint8_t* buf, uint32_t count);
// Return a pointer to module-owned path storage, valid until shutdown/reinit.
const char* neo1_platform_disk_path(void);
// Report a latched SDL_QUIT event without consuming it.
bool neo1_platform_should_quit(void);
